### ISSUE TITLE
Sourcemap comment always causing underflow (-30B)

### ISSUE THREAD

**Issue by luwes** [kuldeepkeshwar/size-plugin-core#3]
https://github.com/luwes/rollup-plugin-size/issues/5
Wanted to duplicate this issue here. 

I'm leaning towards that comments should be stripped for calculating the size I think which would require a change here but wanted to check with you.

The issue is that rollup-plugin-size is comparing only code to file size I guess.
File size includes the comments.

**Comment by kuldeepkeshwar** [comment]
@luwes If I am understanding this correctly, you are saying we should strip off comments from the output files before passing it for compression(gzip)? 

I checked the original issue(luwes/rollup-plugin-size#5), do you have a step-up where it is happening?

**Comment by luwes** [comment]
yes, I think so. we should strip the comments otherwise it will always have a negative bytes value. I'll try it out

**Comment by luwes** [comment]
or actually I'll try it on the rollup-plugin-size side because it doesn't seem to be a problem for https://github.com/GoogleChromeLabs/size-plugin. not sure how webpack handles that.

**Comment by kuldeepkeshwar** [comment]
fixed in https://github.com/luwes/rollup-plugin-size/commit/f5b584f6869b299e13c1cea4dd2f70ef95cd60e2
