### ISSUE TITLE
TypeError: this.compressionSize is not a function

### ISSUE THREAD

**Issue by luwes** [kuldeepkeshwar/size-plugin-core#5]
getting an error `TypeError: this.compressionSize is not a function` when brotli is enabled

looks like line https://github.com/kuldeepkeshwar/size-plugin-core/blob/master/packages/size-plugin-core/size-plugin-core.js#L106

**Comment by kuldeepkeshwar** [comment]
Thanks, @luwes, let me add you to the npm account too. please share your email

**Comment by luwes** [comment]
Thanks @kuldeepkeshwar, that would be useful!

me[at]wesleyluyten(dot)com

**Comment by kuldeepkeshwar** [comment]
@luwes added you. 

I hope we can close this issue now.

**Comment by luwes** [comment]
thanks!
